##Text Vectorization

In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("processed_movies.csv")

In [3]:
movies.head()

,id,title,tags
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

In [6]:
vectors = cv.fit_transform(movies['tags'])

In [7]:
vectors = vectors.toarray()

In [8]:
vectors.shape

(44479, 5000)

In [9]:
stop_words='english'

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(movies['tags']).toarray()

In [26]:
vectors.shape

(5000, 5000)

In [27]:
similarity = cosine_similarity(vectors)

In [28]:
similarity.shape

(5000, 5000)

In [29]:
movies[movies['title'] == 'Interstellar']

Empty DataFrame
Columns: [id, title, tags]
Index: []

In [30]:
movies[movies['title'].str.contains('Inter', case=False, na=False)]

,id,title,tags
93,40154,A Midwinter's Tale,Out of work actor Joe volunteers to help try a...
248,628,Interview with the Vampire,"A vampire relates his epic life story of love,..."
671,40001,Mrs. Winterbourne,Connie Doyle is eighteen and pregnant her boyf...
1435,816,Austin Powers: International Man of Mystery,As a swingin' fashion photographer by day and ...
1629,25994,The Winter Guest,The plot of the story is interactions between ...
3050,3558,"Girl, Interrupted","Set in the changing world of the late 1960's, ..."
3672,15867,Interiors,A look at a dysfunctional family dominated by ...
3952,70199,Dead of Winter,A fledgling actress is lured to a remote mansi...
4279,18988,The Lion in Winter,1183 AD: King Henry II's three sons all want t...

In [31]:
movies['title'].head(20)

0                          Toy Story
1                            Jumanji
2                   Grumpier Old Men
3                  Waiting to Exhale
4        Father of the Bride Part II
5                               Heat
6                            Sabrina
7                       Tom and Huck
8                       Sudden Death
9                          GoldenEye
10            The American President
11       Dracula: Dead and Loving It
12                             Balto
13                             Nixon
14                  Cutthroat Island
15                            Casino
16             Sense and Sensibility
17                        Four Rooms
18    Ace Ventura: When Nature Calls
19                       Money Train
Name: title, dtype: str

In [32]:
movies.shape

(5000, 3)

In [33]:
vectors.shape

(5000, 5000)

In [34]:
movies[movies['title'] == 'Heat']

    id title                                               tags
5  949  Heat  Obsessive master thief, Neil McCauley leads a ...

In [35]:
def recommend(movie):
    
    # Find movie index
    movie_index = movies[movies['title'] == movie].index[0]

    # Get similarity scores
    distances = similarity[movie_index]

    # Pair movie index with similarity score
    movie_list = list(enumerate(distances))

    # Sort by similarity (highest first)
    movie_list = sorted(movie_list, key=lambda x: x[1], reverse=True)

    # Skip the first movie (it's the same movie)
    movie_list = movie_list[1:6]

    # Print recommendations
    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [38]:
movies['title'].sample(20)

1468                                     To Have (Or Not)
765                 My Life and Times With Antonin Artaud
4783                                            The Falls
3668                                      What About Bob?
4925                                      Falling in Love
4005                                      Signs & Wonders
3148                                            The Beach
3059                                            Stalag 17
3720                                             The Cell
3474                                             Dinosaur
4841    The Lord of the Rings: The Fellowship of the Ring
4167                                             Gabriela
1694                                 A Price Above Rubies
576                                 The Brady Bunch Movie
4100                                Bridget Jones's Diary
2966                                          Jagged Edge
3617                                            Communion
859                                The Philadelphia Story
4776                        That Obscure Object of Desire
57                                       The Confessional
Name: title, dtype: str

In [39]:
def recommend(movie):
    movie_data = movies[movies['title'].str.lower() == movie.lower()]

    if movie_data.empty:
        print("Movie not found!")
        return

    movie_index = movie_data.index[0]

    distances = similarity[movie_index]

    movie_list = list(enumerate(distances))

    movie_list = sorted(movie_list, key=lambda x: x[1], reverse=True)[1:6]

    print(f"\nRecommendations for '{movie}':\n")

    for i in movie_list:
        print(movies.iloc[i[0]].title)